version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: tourist-expert-backend-prod
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SHEET_ID=${SHEET_ID:-1Pxl4hiuPvVcCBXIakqzsBzO9IYpo635ZbHfHsdj1c5Y}
      - GID=${GID:-1095660313}
      - PORT=5000
      - ADMIN_KEY=${ADMIN_KEY:-admin-secret}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5656/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: tourist-expert-frontend-prod
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://backend:5656/api
    depends_on:
      - backend
    restart: unless-stopped